### PR TITLE
docs: add self-host guide

### PR DESCRIPTION
**Pull request by arthurdenner**
The `self-hosting.md` file contains an improved description of my notes when deploying a custom instance.

I did _not_ cover all the environment variables as I didn't configure all of them. Feel free to add them here or later in another PR.

I tried my best to guess how to use the `hyperdocs` components, please double-check. Is there a way to preview the docs? I couldn't find it.

Again, feel free to change the guide or improve it later since you know the project way better.
What I wrote takes one from zero to deploy but doesn't cover everything.

### CODE REVIEW

**Comment by arthurdenner** [comment]
I put this `docs/self-host` branch as the default in my fork and managed to deploy it on hyperdocs.
However, it's returning 404 for the new page so I probably did something wrong:
https://hyperdocs.netlify.app/arthurdenner-staticshield/docs/self-hosting

**Comment by Lalit2005** [comment]
Thanks for taking time and effort for improving the docs ❤️ 
The docs for self hosting seems to have no problem.

> I tried my best to guess how to use the hyperdocs components, please double-check. Is there a way to preview the docs? I couldn't find it.

You can preview the markdown code [here](https://hyperdocs.netlify.app/playground).  
I fixed some tiny mistakes in 3aa8664

---

>I put this docs/self-host branch as the default in my fork and managed to deploy it on hyperdocs.
However, it's returning 404 for the new page so I probably did something wrong:

Yeah, Hyperdocs fetches content from `master` branch. So the 404 will vanish after merging into `master`.

**Review by Lalit2005 — APPROVED** [review]

**Comment by arthurdenner** [comment]
Good to know about the playground, thanks! I just had the idea to add a sort of preview command to the CLI which would open the selected file in the playground with its content - what do you think?

The [docs site](https://staticshield.vercel.app/docs) hasn't been updated yet, I'm not sure why.

**Comment by Lalit2005** [comment]
> The [docs site](https://staticshield.vercel.app/docs) hasn't been updated yet, I'm not sure why.

The docs regeneration failed because of lang of a code block was set to `.env`
image

It's fixed in 33e657d4644b7f5d9f011e6b63771ccaa6f24d25

---

> Good to know about the playground, thanks! I just had the idea to add a sort of preview command to the CLI which would open the selected file in the playground with its content - what do you think?

Seems like a nice feature idea for [Hyperdocs](/lalit2005/hyperdocs)!

**Pull request merged**
